AllCops:
  TargetRubyVersion: 2.3

Style/Next:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

# The magic comment is at the top. Below the top is the bloody licenses, having
# a space in between looks like shit. The motivation of this style rule is so
# you don't glue actual code comments to the magic comment, we don't do that
# as we use a freeer license than most of Ruby code and need a licenses header
# to properly license!
# https://github.com/bbatsov/ruby-style-guide#magic-comments
Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - jenkins-jobs/*

Metrics/MethodLength:
  Exclude:
    - jenkins-jobs/*

# Style suggestion is to use activesupport to be able to indent heredocs. I say
# fuck this suggestion. I am not going to require some stupid gem to be able to
# indent heredocs. Ruby 2.3 will solve this with <<~ heredocs.
Layout/IndentHeredoc:
  Enabled: false

# We have plenty of system(*%w(....)) which is good to have because
# ['foo', 'mweo', 'asdf'] is cumbersome AF to write.
Lint/UnneededSplatExpansion:
  Enabled: false

# We generally load only trusted yaml sources produced by us or adjacent KDE
# services (in fact, at the time of writing only us as foreign services
# are generally giving json over the wire)
Security/YAMLLoad:
  Enabled: false

# This is not a web application. If we can't trust the data we open then we may
# as well quit our jobs and become bards traveling the lands to sing the tales
# of Brave Sir Robin.
Security/Open:
  Enabled: false
